import {
  Project,
  ProductPositioning,
  CustomerPersona,
  SEOAuditResult,
  KeywordItem,
  CompetitorInsight,
  ContentOpportunity,
  CampaignItem,
  ActionTask,
  GrowthAnalyticsData,
  GeneratedContent,
} from "../types";

export const DEMO_PROJECT: Project = {
  id: "demo-urbannest",
  name: "UrbanNest Interiors",
  productName: "Premium Home Interior Design Services",
  industry: "Home & Interior Design",
  websiteUrl: "https://urbannest-design.demo",
  location: "Nagpur, MH",
  description: "Modern modular kitchen, luxury living rooms, and complete residential interior architectural execution tailored for modern Indian homeowners.",
  customerType: "B2C",
  targetAge: "28-45",
  customerInterests: "Home Decor, Architecture, Modular Kitchens, Smart Homes, Renovation",
  customerPainPoints: "Pricing ambiguity, delayed contractor handovers, poor quality finishing, lack of 3D preview transparency",
  primaryGoal: "Lead Generation & Client Acquisition",
  budgetRange: "₹5,000,000 - ₹15,000,000 budget per project",
  timeline: "3 Months Growth Sprint",
  healthScore: 82,
  gtmScore: 85,
  seoScore: 74,
  contentScore: 88,
  presenceScore: 69,
  createdAt: "2026-10-01T10:00:00Z",
};

export const DEMO_POSITIONING: ProductPositioning = {
  product: "UrbanNest Luxury Home Interiors",
  targetAudience: "New Homeowners & Villa Buyers in Tier-2/Tier-1 Tech Hubs (e.g. Nagpur)",
  coreProblem: "Homeowners struggle with unreliable contractors, unfulfilled design promises, and hidden costs.",
  valueProposition: "Turnkey 3D-assisted luxury home interiors delivered strictly in 45 days with zero cost overruns.",
  differentiator: "Transparent fixed-price contracting, 10-year warranty, and real-time 3D VR previews before construction.",
  oneLineValProp: "Dream luxury home interiors crafted with precision engineering and delivered in 45 days guaranteed.",
  shortPitch: "UrbanNest Interiors redefines residential design in Nagpur by merging modern Scandinavian minimalism with high-end modular craftsmanship, backed by a strict 45-day handover guarantee.",
  detailedPositioning: "For discerning modern homeowners who value architectural finesse and peace of mind, UrbanNest provides an end-to-end interior design and turnkey execution experience. Unlike traditional contractors and fragmented vendors, UrbanNest offers fixed 3D pricing, VR design walkthroughs, and guaranteed timeline delivery.",
  keyDifferentiators: [
    "45-Day Handover Guarantee with financial penalty clause",
    "100% Custom 3D VR Visualization prior to project signoff",
    "Direct Factory-to-Site Modular Furnishing (Zero middleman markup)",
    "Dedicated Site Architect & Live Daily WhatsApp Progress Reports",
  ],
  marketingChannels: [
    {
      name: "Google Search (Local SEO & PPC)",
      score: 94,
      category: "Search",
      rationale: "High intent keywords like 'interior designer Nagpur' capture users ready to hire within 1-2 weeks.",
    },
    {
      name: "Instagram & Pinterest Showcase",
      score: 91,
      category: "Social",
      rationale: "Interior design is highly visual. Short video reels of before/after home transformations drive high engagement.",
    },
    {
      name: "Local Business Directories & Maps",
      score: 83,
      category: "Organic",
      rationale: "Google Business Profile optimization drives immediate phone inquiries from nearby residential project handovers.",
    },
    {
      name: "Real Estate Builder Alliances",
      score: 79,
      category: "Outreach",
      rationale: "Co-marketing with premium housing township developers reaches new property buyers right at possession.",
    },
    {
      name: "Facebook & Meta Retargeting Ads",
      score: 72,
      category: "Paid",
      rationale: "Retarget website visitors with video testimonials to convert undecided prospects.",
    },
  ],
};

export const DEMO_PERSONAS: CustomerPersona[] = [
  {
    id: "p1",
    title: "The Upgrading Tech Professional",
    type: "Primary",
    ageRange: "28-40",
    location: "Nagpur / IT Corridors",
    problem: "Needs complete modern interior design for a newly purchased 3BHK flat, but lacks time to supervise local labor.",
    goals: "A stylish, space-efficient home with a smart modular kitchen that impresses friends.",
    painPoints: "Uncertainty about pricing, fear of cheap materials, delayed delivery.",
    buyingTriggers: "Possession letter received from builder; moving deadline approaching.",
    preferredChannels: ["Google Search", "Instagram Reels", "WhatsApp Consultation"],
    recommendedMessage: "Luxury 3BHK Interiors Delivered in 45 Days with 10-Year Warranty & Zero Hidden Costs.",
  },
  {
    id: "p2",
    title: "The Villa Owner & Business Executive",
    type: "Secondary",
    ageRange: "40-58",
    location: "Nagpur Civil Lines / Besa / Manish Nagar",
    problem: "Wants premium bespoke woodwork, Italian marble accents, and smart lighting for a sprawling independent duplex.",
    goals: "Uncompromising luxury, high architectural value, seamless site management.",
    painPoints: "Local carpenters lacking modern finish standards; poor project tracking.",
    buyingTriggers: "Architectural slab completion; recommendation from elite network.",
    preferredChannels: ["Personal Referral", "Google Maps Reviews", "Direct Studio Walk-in"],
    recommendedMessage: "Bespoke Architectural Luxury for Independent Villas — Designed & Managed by Senior Architects.",
  },
  {
    id: "p3",
    title: "The NRI / Outstation Property Investor",
    type: "Emerging",
    ageRange: "32-50",
    location: "Pune / Mumbai / International (Investing in Nagpur)",
    problem: "Owns luxury real estate locally but cannot be physically present to manage interior vendors.",
    goals: "Turnkey furnished apartment ready for personal visits or high-end tenant rental.",
    painPoints: "Inability to verify material quality on site; communication bottlenecks.",
    buyingTriggers: "High rental yield opportunity; need for turnkey trusted manager.",
    preferredChannels: ["Virtual Zoom Consultation", "Email Proposals", "YouTube House Tours"],
    recommendedMessage: "100% Remote Turnkey Interior Execution with Live Video Updates & Dedicated Project Manager.",
  },
];

export const DEMO_SEO_AUDIT: SEOAuditResult = {
  url: "https://urbannest-design.demo",
  score: 74,
  categories: {
    technical: 82,
    onPage: 68,
    content: 75,
    keywords: 65,
    internalLinking: 70,
    metaInfo: 62,
    performance: 88,
  },
  onPageAudit: {
    currentTitle: "Home Services | UrbanNest",
    recommendedTitle: "Best Interior Designers in Nagpur | Luxury Modular Interiors | UrbanNest",
    titleRationale: "The current title lacks target geographical terms ('Nagpur') and high-intent commercial keywords ('Interior Designers', 'Modular Interiors').",
    currentMetaDesc: "We offer interior design services for homes and kitchens.",
    recommendedMetaDesc: "Transform your home with Nagpur's top-rated interior designers. 45-day guaranteed completion, 3D VR design previews & 10-year warranty. Book a free consultation!",
    metaDescRationale: "The recommended description adds strong call-to-action triggers (45-day completion, free consultation) and localized search signals.",
    h1: "Welcome to UrbanNest Design Studio",
    recommendedH1: "Bespoke Home Interior Design & Modular Kitchen Services in Nagpur",
    h2Count: 4,
    h3Count: 8,
    keywordUsage: "Low concentration of local transactional phrases ('interior designer in Nagpur', 'modular kitchen cost Nagpur').",
    contentLength: 640,
    imagesCount: 14,
    imagesWithoutAlt: 6,
    internalLinksCount: 5,
    externalLinksCount: 2,
  },
  recommendations: [
    {
      id: "seo-1",
      category: "On-Page SEO",
      title: "Optimize Homepage Title & H1 Tag with Local Geo-Modifiers",
      impact: "High",
      description: "Including 'Nagpur' and 'Interior Designers' in primary tags improves rank for high-intent queries by up to 40%.",
      actionStep: "Update title tag to 'Best Interior Designers in Nagpur | UrbanNest' and H1 to include localized keyword phrases.",
    },
    {
      id: "seo-2",
      category: "Content & Landing Pages",
      title: "Create Dedicated Neighborhood Service Pages",
      impact: "High",
      description: "Target specific high-density residential hubs (e.g. 'Interior Designers in Besa', 'Interior Designers in Civil Lines').",
      actionStep: "Publish 4 hyper-local landing pages with tailored portfolio photos and customer testimonials.",
    },
    {
      id: "seo-3",
      category: "Image Optimization",
      title: "Add Descriptive Alt Tags to Portfolio Gallery Images",
      impact: "Medium",
      description: "6 out of 14 images lack alt attributes, missing out on Google Image Search traffic.",
      actionStep: "Add alt tags like 'modular-kitchen-design-nagpur-urbannest.jpg' to all project showcase images.",
    },
    {
      id: "seo-4",
      category: "Local SEO",
      title: "Claim and Optimize Google Business Profile",
      impact: "High",
      description: "Local Map Pack accounts for 60%+ of immediate inbound calls for interior design.",
      actionStep: "Gather 15+ verified customer reviews with photos and add complete service menu listings.",
    },
  ],
};

export const DEMO_KEYWORDS: KeywordItem[] = [
  {
    id: "k1",
    keyword: "interior designer in nagpur",
    searchIntent: "Commercial",
    competition: "High",
    relevance: 98,
    priority: "High",
    recommendedPage: "/interior-designers-nagpur",
    estMonthlyVolume: 2400,
  },
  {
    id: "k2",
    keyword: "home interior design nagpur",
    searchIntent: "Commercial",
    competition: "High",
    relevance: 95,
    priority: "High",
    recommendedPage: "/",
    estMonthlyVolume: 1900,
  },
  {
    id: "k3",
    keyword: "modular kitchen cost in nagpur",
    searchIntent: "Transactional",
    competition: "Medium",
    relevance: 92,
    priority: "High",
    recommendedPage: "/modular-kitchen-calculator",
    estMonthlyVolume: 1200,
  },
  {
    id: "k4",
    keyword: "best 3bhk interior design ideas",
    searchIntent: "Informational",
    competition: "Medium",
    relevance: 84,
    priority: "Medium",
    recommendedPage: "/blog/3bhk-interior-design-guide",
    estMonthlyVolume: 4800,
  },
  {
    id: "k5",
    keyword: "living room interior design packages",
    searchIntent: "Commercial",
    competition: "Medium",
    relevance: 88,
    priority: "High",
    recommendedPage: "/pricing-packages",
    estMonthlyVolume: 1500,
  },
  {
    id: "k6",
    keyword: "luxury villa architects in nagpur",
    searchIntent: "Transactional",
    competition: "Low",
    relevance: 80,
    priority: "Medium",
    recommendedPage: "/luxury-villas",
    estMonthlyVolume: 720,
  },
];

export const DEMO_COMPETITORS: CompetitorInsight[] = [
  {
    id: "c1",
    name: "Livspace Nagpur Showcase",
    url: "https://livspace-nagpur.demo",
    seoScore: 84,
    contentScore: 89,
    keywordScore: 87,
    presenceScore: 92,
    positioning: "Mass market pan-India home interior chain with standardized catalogue designs.",
    strengths: ["Strong brand awareness", "High organic keyword coverage", "Large photo library"],
    weaknesses: ["Impersonal customer service", "Higher hidden charges", "Subcontracted site workers"],
    winStrategy: "Emphasize local architect availability, fixed 45-day delivery guarantee, and zero subcontracting quality.",
  },
  {
    id: "c2",
    name: "Homelane Design Studio",
    url: "https://homelane-demo.com",
    seoScore: 79,
    contentScore: 82,
    keywordScore: 81,
    presenceScore: 85,
    positioning: "Budget-friendly modular kitchen & 45-day delivery focus.",
    strengths: ["Clear price calculator", "Aggressive social media ad spending"],
    weaknesses: ["Limited custom woodwork options", "Rigid catalog templates"],
    winStrategy: "Position UrbanNest as the premium bespoke alternative for homeowners wanting custom architectural craftsmanship beyond basic catalog boxes.",
  },
  {
    id: "c3",
    name: "Local Architectural Contractors",
    url: "https://nagpur-local-designers.demo",
    seoScore: 58,
    contentScore: 52,
    keywordScore: 60,
    presenceScore: 64,
    positioning: "Traditional independent carpenters & individual freelance architects.",
    strengths: ["Low initial estimates", "Direct local relationships"],
    weaknesses: ["Severe project delays (6+ months)", "No 3D visual preview", "Cost escalation during work"],
    winStrategy: "Highlight 3D VR pre-visualization and penalty-backed timeline commitment.",
  },
];

export const DEMO_CONTENT_OPPORTUNITIES: ContentOpportunity[] = [
  {
    id: "co-1",
    topic: "Complete Cost Breakdown: 3BHK Home Interior Design in Nagpur (2026 Guide)",
    searchIntent: "Commercial / High Intent",
    targetKeyword: "3bhk interior design cost nagpur",
    priority: "High",
    suggestedFormat: "Landing Page",
    estimatedTrafficPotential: "1,400 monthly visitors",
  },
  {
    id: "co-2",
    topic: "7 Critical Errors Homeowners Make When Choosing Modular Kitchen Finishes",
    searchIntent: "Informational",
    targetKeyword: "modular kitchen finish comparison",
    priority: "High",
    suggestedFormat: "Blog Post",
    estimatedTrafficPotential: "2,100 monthly visitors",
  },
  {
    id: "co-3",
    topic: "Inside a 2,400 sq.ft. Minimalist Luxury Villa in Nagpur [Video & Photo Tour]",
    searchIntent: "Navigational / Visual",
    targetKeyword: "luxury interior walkthrough nagpur",
    priority: "Medium",
    suggestedFormat: "Social Series",
    estimatedTrafficPotential: "8,500 video impressions",
  },
];

export const DEMO_ACTION_PLAN: ActionTask[] = [
  {
    id: "task-1",
    week: 1,
    title: "Update Homepage Title Tag & Local Schema Markup",
    category: "SEO",
    priority: "High",
    dueDate: "Week 1 - Day 3",
    status: "COMPLETED",
    description: "Add geo-targeted meta title tags and Schema.org LocalBusiness JSON-LD markup to boost local map rankings.",
  },
  {
    id: "task-2",
    week: 1,
    title: "Set Up Google Business Profile & Request 10 Client Reviews",
    category: "Outreach",
    priority: "High",
    dueDate: "Week 1 - Day 5",
    status: "COMPLETED",
    description: "Optimize profile categories, uploaded high-resolution project portfolio photos, and send review link to recent handover clients.",
  },
  {
    id: "task-3",
    week: 2,
    title: "Publish 3BHK Cost Calculator Landing Page",
    category: "Content",
    priority: "High",
    dueDate: "Week 2 - Day 4",
    status: "IN_PROGRESS",
    description: "Develop an interactive interior cost estimator widget that captures prospective client leads in exchange for instant PDF estimate.",
  },
  {
    id: "task-4",
    week: 2,
    title: "Launch Meta Instagram Before/After Transformation Reel Campaign",
    category: "Outreach",
    priority: "Medium",
    dueDate: "Week 2 - Day 7",
    status: "PENDING",
    description: "Run targeted micro-budget Instagram video ads aimed at new property owners within a 15km radius of top township handover zones.",
  },
  {
    id: "task-5",
    week: 3,
    title: "Partner with Top 3 Local Real Estate Township Developers",
    category: "Outreach",
    priority: "High",
    dueDate: "Week 3 - Day 5",
    status: "PENDING",
    description: "Distribute exclusive 'New Homeowner Welcome Vouchers' ($500 interior credit) in builder possession welcome kits.",
  },
  {
    id: "task-6",
    week: 4,
    title: "Conduct Monthly SEO & Inbound Lead Conversion Audit",
    category: "Optimization",
    priority: "Medium",
    dueDate: "Week 4 - Day 7",
    status: "PENDING",
    description: "Review Google Search Console keyword queries, conversion rates, and ROI per acquisition channel.",
  },
];

export const DEMO_ANALYTICS: GrowthAnalyticsData = {
  summary: [
    { name: "Monthly Visitors", current: 8420, previous: 5100, unit: "", change: 65.1, trend: "up" },
    { name: "Qualified Inbound Leads", current: 142, previous: 86, unit: "", change: 65.1, trend: "up" },
    { name: "Consultation Bookings", current: 38, previous: 21, unit: "", change: 80.9, trend: "up" },
    { name: "Est. Pipeline Revenue", current: 485000, previous: 290000, unit: "$", change: 67.2, trend: "up" },
  ],
  trafficTrend: [
    { date: "May", organic: 1200, paid: 800, direct: 400 },
    { date: "Jun", organic: 1800, paid: 1100, direct: 600 },
    { date: "Jul", organic: 2600, paid: 1400, direct: 900 },
    { date: "Aug", organic: 3400, paid: 1900, direct: 1200 },
    { date: "Sep", organic: 4500, paid: 2200, direct: 1720 },
  ],
  leadConversions: [
    { month: "May", leads: 42, signups: 8 },
    { month: "Jun", leads: 68, signups: 14 },
    { month: "Jul", leads: 95, signups: 22 },
    { month: "Aug", leads: 118, signups: 29 },
    { month: "Sep", leads: 142, signups: 38 },
  ],
  channelShare: [
    { name: "Google Search (SEO)", percentage: 45 },
    { name: "Instagram Reels & Ads", percentage: 28 },
    { name: "Google Business Maps", percentage: 15 },
    { name: "Referrals & Alliances", percentage: 12 },
  ],
  keywordRankings: [
    { keyword: "interior designer nagpur", rank: 3, change: 4 },
    { keyword: "home interior design nagpur", rank: 2, change: 5 },
    { keyword: "modular kitchen cost nagpur", rank: 1, change: 2 },
    { keyword: "best 3bhk interiors nagpur", rank: 4, change: 6 },
    { keyword: "luxury villa design nagpur", rank: 5, change: 3 },
  ],
};

// Generator helper for custom user projects in Demo/Mock Mode
export function generateMockStrategyForProject(projectInfo: Partial<Project>): {
  positioning: ProductPositioning;
  personas: CustomerPersona[];
  seoAudit: SEOAuditResult;
  keywords: KeywordItem[];
  competitors: CompetitorInsight[];
  contentOpportunities: ContentOpportunity[];
  actionPlan: ActionTask[];
} {
  const name = projectInfo.name || "Growth Project";
  const product = projectInfo.productName || "AI SaaS Solution";
  const location = projectInfo.location || "Global";
  const industry = projectInfo.industry || "Software & Tech";
  const url = projectInfo.websiteUrl || "https://example.com";

  return {
    positioning: {
      product: product,
      targetAudience: projectInfo.customerInterests || `High-value customers seeking ${industry} solutions in ${location}`,
      coreProblem: projectInfo.customerPainPoints || `Outdated manual workflows and high costs in ${industry}.`,
      valueProposition: `AI-driven automated platform designed specifically for ${industry} growth.`,
      differentiator: "10x faster execution, predictive AI insights, and transparent ROI metrics.",
      oneLineValProp: `Supercharge your ${industry} workflow with ${name}'s intelligent platform.`,
      shortPitch: `${name} provides an all-in-one growth architecture for ${product} targeting ${location} markets.`,
      detailedPositioning: `For modern organizations in ${industry}, ${name} delivers a streamlined, high-performance platform that replaces legacy manual approaches. Unlike fragmented competitors, ${name} unifies analysis, execution, and performance analytics into a single command center.`,
      keyDifferentiators: [
        "AI-Powered Real-time Market Intelligence",
        "Automated Lead & Traffic Generation Workflows",
        "Customized Industry Analytics & Reporting",
        "Enterprise-grade Security & Rapid Deployment",
      ],
      marketingChannels: [
        { name: "Search Engine Optimization (SEO)", score: 92, category: "Search", rationale: "Captures steady organic search demand from high-intent buyers." },
        { name: "LinkedIn & B2B Content Marketing", score: 88, category: "Social", rationale: "Establishes authority and connects directly with key decision makers." },
        { name: "Targeted PPC & Search Ads", score: 84, category: "Paid", rationale: "Drives immediate qualified inbound trial signups." },
        { name: "Email Nurture Sequences", score: 76, category: "Outreach", rationale: "Converts leads into recurring customers over a 30-day onboarding funnel." },
      ],
    },
    personas: [
      {
        id: "p-custom-1",
        title: `The Primary Decision Maker (${industry})`,
        type: "Primary",
        ageRange: "30-50",
        location: location,
        problem: `Needs an efficient, reliable way to scale ${product} results.`,
        goals: "Maximize growth efficiency while reducing overhead costs.",
        painPoints: "Fragmented tools, slow manual processes, lack of clear metrics.",
        buyingTriggers: "Quarterly growth planning or system breakdown.",
        preferredChannels: ["Google Search", "Industry Reports", "LinkedIn"],
        recommendedMessage: `Scale your ${industry} outcomes effortlessly with ${name}.`,
      },
      {
        id: "p-custom-2",
        title: "The Tech-Savvy Operator",
        type: "Secondary",
        ageRange: "25-40",
        location: location,
        problem: "Wants modern software tools that save time and automate repetitive work.",
        goals: "Faster execution speed and seamless team collaboration.",
        painPoints: "Clunky UI, poor integration, slow setup.",
        buyingTriggers: "Free trial discovery or colleague recommendation.",
        preferredChannels: ["Product Hunt", "Twitter/X", "YouTube Tutorials"],
        recommendedMessage: "The fastest way to automate your daily growth workflows.",
      },
    ],
    seoAudit: {
      url: url,
      score: 78,
      categories: {
        technical: 84,
        onPage: 75,
        content: 80,
        keywords: 72,
        internalLinking: 76,
        metaInfo: 70,
        performance: 85,
      },
      onPageAudit: {
        currentTitle: `${name} | Official Website`,
        recommendedTitle: `${product} Services & Platform | ${name}`,
        titleRationale: "Added primary industry keywords to improve search indexing relevance.",
        currentMetaDesc: `Learn more about ${name}.`,
        recommendedMetaDesc: `Discover ${name} - the premier ${product} platform in ${location}. Start growing your business with AI today!`,
        metaDescRationale: "Includes compelling value proposition and direct call to action.",
        h1: `${product} Solutions`,
        recommendedH1: `Next-Generation ${product} for Modern ${industry}`,
        h2Count: 5,
        h3Count: 7,
        keywordUsage: "Good baseline keywords, opportunity for localized phrases.",
        contentLength: 850,
        imagesCount: 10,
        imagesWithoutAlt: 2,
        internalLinksCount: 8,
        externalLinksCount: 3,
      },
      recommendations: [
        {
          id: "rec-1",
          category: "On-Page SEO",
          title: "Optimize Meta Title & Main Headings",
          impact: "High",
          description: "Align page titles with primary user search queries.",
          actionStep: `Update title tag to include '${product}' and '${location}'.`,
        },
        {
          id: "rec-2",
          category: "Content",
          title: "Add Industry Case Studies & FAQs",
          impact: "High",
          description: "Structured content builds trust and earns rich search snippets.",
          actionStep: "Publish 3 client case studies and an interactive FAQ section.",
        },
      ],
    },
    keywords: [
      {
        id: "kw-1",
        keyword: `${product.toLowerCase()} in ${location.toLowerCase()}`,
        searchIntent: "Commercial",
        competition: "High",
        relevance: 96,
        priority: "High",
        recommendedPage: "/services",
        estMonthlyVolume: 1800,
      },
      {
        id: "kw-2",
        keyword: `best ${industry.toLowerCase()} platform`,
        searchIntent: "Commercial",
        competition: "Medium",
        relevance: 91,
        priority: "High",
        recommendedPage: "/",
        estMonthlyVolume: 2400,
      },
      {
        id: "kw-3",
        keyword: `how to choose ${product.toLowerCase()}`,
        searchIntent: "Informational",
        competition: "Low",
        relevance: 85,
        priority: "Medium",
        recommendedPage: "/blog/buyers-guide",
        estMonthlyVolume: 1100,
      },
    ],
    competitors: [
      {
        id: "comp-1",
        name: `${industry} Leader Alpha`,
        url: "https://competitor-alpha.demo",
        seoScore: 86,
        contentScore: 88,
        keywordScore: 85,
        presenceScore: 90,
        positioning: "Established legacy incumbent with higher price point.",
        strengths: ["Large existing market share", "Strong backlink authority"],
        weaknesses: ["Outdated legacy interface", "Slow customer support"],
        winStrategy: "Highlight modern AI automation, superior UI ease-of-use, and flexible pricing.",
      },
      {
        id: "comp-2",
        name: "Fast-Growing Challenger",
        url: "https://competitor-beta.demo",
        seoScore: 78,
        contentScore: 82,
        keywordScore: 79,
        presenceScore: 81,
        positioning: "Low-cost alternative focusing on basic core features.",
        strengths: ["Aggressive pricing", "Simple onboarding"],
        weaknesses: ["Lacks advanced analytics and customization"],
        winStrategy: "Demonstrate deeper enterprise features, comprehensive reporting, and AI intelligence.",
      },
    ],
    contentOpportunities: [
      {
        id: "co-custom-1",
        topic: `The Ultimate 2026 Guide to ${product} in ${location}`,
        searchIntent: "Commercial",
        targetKeyword: `${product.toLowerCase()} guide`,
        priority: "High",
        suggestedFormat: "Guide",
        estimatedTrafficPotential: "1,800 monthly visitors",
      },
      {
        id: "co-custom-2",
        topic: `Top 5 Mistakes to Avoid in ${industry} Growth`,
        searchIntent: "Informational",
        targetKeyword: `${industry.toLowerCase()} growth tips`,
        priority: "Medium",
        suggestedFormat: "Blog Post",
        estimatedTrafficPotential: "1,200 monthly visitors",
      },
    ],
    actionPlan: [
      {
        id: "act-1",
        week: 1,
        title: "Optimize Meta Tags & Homepage Architecture",
        category: "SEO",
        priority: "High",
        dueDate: "Week 1 - Day 3",
        status: "COMPLETED",
        description: "Align primary landing page titles and meta descriptions with core keywords.",
      },
      {
        id: "act-2",
        week: 2,
        title: "Launch Core Content Pillar & Buyer's Guide",
        category: "Content",
        priority: "High",
        dueDate: "Week 2 - Day 5",
        status: "IN_PROGRESS",
        description: "Publish comprehensive industry guide to capture mid-funnel search intent.",
      },
      {
        id: "act-3",
        week: 3,
        title: "Deploy Targeted Inbound Lead Campaign",
        category: "Outreach",
        priority: "Medium",
        dueDate: "Week 3 - Day 4",
        status: "PENDING",
        description: "Execute multi-channel campaign targeting high-relevance customer segments.",
      },
      {
        id: "act-4",
        week: 4,
        title: "Review Analytics & Conversion Funnel",
        category: "Optimization",
        priority: "Medium",
        dueDate: "Week 4 - Day 7",
        status: "PENDING",
        description: "Audit traffic quality, bounce rates, and lead conversion points.",
      },
    ],
  };
}
